services:
  app:
    platform: linux/arm64
    build:
      context: ./
      dockerfile: dockerfile.app
    container_name: smash-hit-web-app
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - server

  server:
    platform: linux/arm64
    build:
      context: ./
      dockerfile: dockerfile.server
    container_name: smash-hit-server
    environment:
      - PORT=8080
    volumes:
      - ./server:/app
      - /app/node_modules
    ports:
      - "8080:8080"

  test:
    platform: linux/arm64
    build:
      context: ./
      dockerfile: dockerfile.testable
    container_name: smash-hit-web-test
    environment:
      - NODE_ENV=testable
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "3001:3001"

networks:
  default:
    name: smash-hit-web


